name: Sync Shadowrocket ADBlock Rules

on:
  schedule:
    - cron: '0 2 * * *' # This will run the action every day at 02:00 AM UTC
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetch the latest rules from Johnshall/Shadowrocket-ADBlock-Rules-Forever
        run: |
          git clone --depth=1 --branch=release https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever.git temp_repo
          cp temp_repo/sr_top500_whitelist_ad.conf sr_top500_whitelist_ad.conf
          cp temp_repo/sr_cnip_ad.conf sr_cnip_ad.conf

      - name: Commit and push changes
        run: |
          git config --global user.name "tst-pandit-pan"
          git config --global user.email "panditpan1219@gmail.com"
          git add sr_top500_whitelist_ad.conf sr_cnip_ad.conf
          git commit -m "Update Shadowrocket ADBlock rules"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
