name: Update PROXYALL_AD.conf

on:
  schedule:
    - cron: '30 20 * * *' # 4:30 AM Hong Kong Time (UTC+8)
  workflow_dispatch:

jobs:
  update-proxy-config:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Copy and modify the file
      - name: Copy and modify PROXYALL_AD.conf
        run: |
          # Ensure TMP_Source/sr_proxy_banad.conf exists
          if [ ! -f TMP_Source/sr_proxy_banad.conf ]; then
            echo "sr_proxy_banad.conf is missing!"
            exit 1
          fi
          
          # Copy sr_proxy_banad.conf to PROXYALL_AD.conf
          cp TMP_Source/sr_proxy_banad.conf PROXYALL_AD.conf
          
          # Replace line 7 with ipv6 = true
          sed -i '7s/.*/ipv6 = true/' PROXYALL_AD.conf
          
          # Replace line 11 with dns-server = 1.1.1.1, 223.5.5.5
          sed -i '11s/.*/dns-server = 1.1.1.1, 223.5.5.5/' PROXYALL_AD.conf

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add PROXYALL_AD.conf
          git commit -m "Update PROXYALL_AD.conf from sr_proxy_banad.conf"
          git push
