name: Update CN_AD.conf

on:
  schedule:
    - cron: '30 20 * * *' # 4:30 AM Hong Kong Time (UTC+8)
  workflow_dispatch:

jobs:
  update-cn-config:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Copy and modify the file
      - name: Copy and modify CN_AD.conf
        run: |
          # Ensure TMP_Sources/sr_cnip_ad.conf exists
          if [ ! -f TMP_Sources/sr_cnip_ad.conf ]; then
            echo "sr_cnip_ad.conf is missing!"
            exit 1
          fi
          
          # Copy sr_cnip_ad.conf to CN_AD.conf
          cp TMP_Sources/sr_cnip_ad.conf CN_AD.conf
          
          # Replace line 7 with ipv6 = true
          sed -i '7s/.*/ipv6 = true/' CN_AD.conf
          
          # Replace line 11 with dns-server = 1.1.1.1, 223.5.5.5
          sed -i '11s/.*/dns-server = 1.1.1.1, 223.5.5.5/' CN_AD.conf

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add CN_AD.conf
          git commit -m "Updated CN_AD.conf"
          git push
